language: go

go:
 - 1.6

install:
 - go get github.com/mattn/goveralls
 - go get github.com/gogo/protobuf/proto
 - go get github.com/cloudflare/golz4
 - go get github.com/golang/glog

script:
 - $HOME/gopath/bin/goveralls -service=travis-ci
